// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace SistemaU.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaU.Modelos.Certificado", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("InscripcionCodigo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("esValido")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("Codigo");

                    b.HasIndex("InscripcionCodigo")
                        .IsUnique();

                    b.ToTable("Certificados");
                });

            modelBuilder.Entity("SistemaU.Modelos.Evento", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("lugar")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Codigo");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("SistemaU.Modelos.Inscripcion", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<string>("EstadoDeInscripcion")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("EventoCodigo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("ParticipanteCodigo")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Codigo");

                    b.HasIndex("EventoCodigo");

                    b.HasIndex("ParticipanteCodigo");

                    b.ToTable("Inscripciones");
                });

            modelBuilder.Entity("SistemaU.Modelos.Pago", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("InscripcionCodigo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("MetodoDePago")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<double>("Monto")
                        .HasColumnType("BINARY_DOUBLE");

                    b.HasKey("Codigo");

                    b.HasIndex("InscripcionCodigo");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("SistemaU.Modelos.Participante", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Codigo");

                    b.ToTable("Participantes");
                });

            modelBuilder.Entity("SistemaU.Modelos.Ponente", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Biografia")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("EventoCodigo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Codigo");

                    b.HasIndex("EventoCodigo");

                    b.ToTable("Ponentes");
                });

            modelBuilder.Entity("SistemaU.Modelos.Seccion", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<int>("EventoCodigo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Codigo");

                    b.HasIndex("EventoCodigo");

                    b.ToTable("Secciones");
                });

            modelBuilder.Entity("SistemaU.Modelos.Certificado", b =>
                {
                    b.HasOne("SistemaU.Modelos.Inscripcion", "Inscripciones")
                        .WithOne("Certificados")
                        .HasForeignKey("SistemaU.Modelos.Certificado", "InscripcionCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("SistemaU.Modelos.Inscripcion", b =>
                {
                    b.HasOne("SistemaU.Modelos.Evento", "Eventos")
                        .WithMany("Inscripciones")
                        .HasForeignKey("EventoCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaU.Modelos.Participante", "Participantes")
                        .WithMany("Inscripciones")
                        .HasForeignKey("ParticipanteCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eventos");

                    b.Navigation("Participantes");
                });

            modelBuilder.Entity("SistemaU.Modelos.Pago", b =>
                {
                    b.HasOne("SistemaU.Modelos.Inscripcion", "Inscripciones")
                        .WithMany("Pagos")
                        .HasForeignKey("InscripcionCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("SistemaU.Modelos.Ponente", b =>
                {
                    b.HasOne("SistemaU.Modelos.Evento", "Eventos")
                        .WithMany("Ponentes")
                        .HasForeignKey("EventoCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("SistemaU.Modelos.Seccion", b =>
                {
                    b.HasOne("SistemaU.Modelos.Evento", "Eventos")
                        .WithMany("Secciones")
                        .HasForeignKey("EventoCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("SistemaU.Modelos.Evento", b =>
                {
                    b.Navigation("Inscripciones");

                    b.Navigation("Ponentes");

                    b.Navigation("Secciones");
                });

            modelBuilder.Entity("SistemaU.Modelos.Inscripcion", b =>
                {
                    b.Navigation("Certificados");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("SistemaU.Modelos.Participante", b =>
                {
                    b.Navigation("Inscripciones");
                });
#pragma warning restore 612, 618
        }
    }
}
